import React from "react";
import Square from "../components/Square";

function ChessBoard(props) {
  if (props.perspective === "white") {
    return (
      <table className="center">
        <tbody>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[0][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[1][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[2][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[3][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[4][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[5][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[6][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][7]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[7][0]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][7]}
                size={props.size}
              />
            </td>
          </tr>
        </tbody>
      </table>
    );
  } else {
    return (
      <table>
        <tbody>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[7][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[7][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[7][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[6][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[6][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[6][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[5][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[5][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[5][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[4][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[4][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[4][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[3][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[3][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[3][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[2][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[2][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[2][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="dark"
                piece={props.position[1][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[1][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[1][0]}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                color="light"
                piece={props.position[0][7]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][6]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][5]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][4]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][3]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][2]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="light"
                piece={props.position[0][1]}
                size={props.size}
              />
            </td>
            <td>
              <Square
                color="dark"
                piece={props.position[0][0]}
                size={props.size}
              />
            </td>
          </tr>
        </tbody>
      </table>
    );
  }
}

export default ChessBoard;
