import React, { useState } from "react";
import Square from "../components/Square";

function ChessBoard(props) {
  const [possibleMoves, setPossibleMoves] = useState([]);
  const [clickToMove, setClickToMove] = useState(false);
  const [fromSquare, setFromSquare] = useState("");

  const getMoves = startSquare => {
    setPossibleMoves(props.getMoves(startSquare).map(move => move.to));
  };

  const makeMove = move => {
    props.makeMove(move);
    setPossibleMoves([]);
  };

  const onClickHandler = square => {
    if (!clickToMove) {
      getMoves(square);
      setFromSquare(square);
      setClickToMove(true);
    } else {
      makeMove({ from: fromSquare, to: square });
      setClickToMove(false);
    }
  };

  if (props.perspective === "white") {
    return (
      <table className="center" style={{ width: props.size, zIndex: 1 }}>
        <tbody>
          <tr>
            <td>
              <Square
                name="a8"
                color="light"
                piece={props.position[0][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b8"
                color="dark"
                piece={props.position[0][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c8"
                color="light"
                piece={props.position[0][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d8"
                color="dark"
                piece={props.position[0][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e8"
                color="light"
                piece={props.position[0][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f8"
                color="dark"
                piece={props.position[0][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g8"
                color="light"
                piece={props.position[0][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h8"
                color="dark"
                piece={props.position[0][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h8")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a7"
                color="dark"
                piece={props.position[1][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b7"
                color="light"
                piece={props.position[1][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c7"
                color="dark"
                piece={props.position[1][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d7"
                color="light"
                piece={props.position[1][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e7"
                color="dark"
                piece={props.position[1][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f7"
                color="light"
                piece={props.position[1][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g7"
                color="dark"
                piece={props.position[1][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h7"
                color="light"
                piece={props.position[1][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h7")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a6"
                color="light"
                piece={props.position[2][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b6"
                color="dark"
                piece={props.position[2][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c6"
                color="light"
                piece={props.position[2][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d6"
                color="dark"
                piece={props.position[2][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e6"
                color="light"
                piece={props.position[2][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f6"
                color="dark"
                piece={props.position[2][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g6"
                color="light"
                piece={props.position[2][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h6"
                color="dark"
                piece={props.position[2][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h6")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a5"
                color="dark"
                piece={props.position[3][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b5"
                color="light"
                piece={props.position[3][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c5"
                color="dark"
                piece={props.position[3][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d5"
                color="light"
                piece={props.position[3][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e5"
                color="dark"
                piece={props.position[3][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f5"
                color="light"
                piece={props.position[3][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g5"
                color="dark"
                piece={props.position[3][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h5"
                color="light"
                piece={props.position[3][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h5")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a4"
                color="light"
                piece={props.position[4][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b4"
                color="dark"
                piece={props.position[4][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c4"
                color="light"
                piece={props.position[4][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d4"
                color="dark"
                piece={props.position[4][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e4"
                color="light"
                piece={props.position[4][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f4"
                color="dark"
                piece={props.position[4][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g4"
                color="light"
                piece={props.position[4][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h4"
                color="dark"
                piece={props.position[4][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h4")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a3"
                color="dark"
                piece={props.position[5][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b3"
                color="light"
                piece={props.position[5][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c3"
                color="dark"
                piece={props.position[5][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d3"
                color="light"
                piece={props.position[5][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e3"
                color="dark"
                piece={props.position[5][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f3"
                color="light"
                piece={props.position[5][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g3"
                color="dark"
                piece={props.position[5][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h3"
                color="light"
                piece={props.position[5][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h3")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a2"
                color="light"
                piece={props.position[6][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b2"
                color="dark"
                piece={props.position[6][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c2"
                color="light"
                piece={props.position[6][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d2"
                color="dark"
                piece={props.position[6][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e2"
                color="light"
                piece={props.position[6][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f2"
                color="dark"
                piece={props.position[6][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g2"
                color="light"
                piece={props.position[6][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h2"
                color="dark"
                piece={props.position[6][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h2")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a1"
                color="dark"
                piece={props.position[7][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b1"
                color="light"
                piece={props.position[7][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c1"
                color="dark"
                piece={props.position[7][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d1"
                color="light"
                piece={props.position[7][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e1"
                color="dark"
                piece={props.position[7][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f1"
                color="light"
                piece={props.position[7][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g1"
                color="dark"
                piece={props.position[7][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="h1"
                color="light"
                piece={props.position[7][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h1")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
        </tbody>
      </table>
    );
  } else {
    return (
      <table className="center">
        <tbody>
          <tr>
            <td>
              <Square
                name="h1"
                color="light"
                piece={props.position[7][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g1"
                color="dark"
                piece={props.position[7][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f1"
                color="light"
                piece={props.position[7][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e1"
                color="dark"
                piece={props.position[7][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d1"
                color="light"
                piece={props.position[7][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c1"
                color="dark"
                piece={props.position[7][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b1"
                color="light"
                piece={props.position[7][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b1")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a1"
                color="dark"
                piece={props.position[7][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a1")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h2"
                color="dark"
                piece={props.position[6][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g2"
                color="light"
                piece={props.position[6][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f2"
                color="dark"
                piece={props.position[6][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e2"
                color="light"
                piece={props.position[6][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d2"
                color="dark"
                piece={props.position[6][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c2"
                color="light"
                piece={props.position[6][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b2"
                color="dark"
                piece={props.position[6][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b2")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a2"
                color="light"
                piece={props.position[6][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a2")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h3"
                color="light"
                piece={props.position[5][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g3"
                color="dark"
                piece={props.position[5][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f3"
                color="light"
                piece={props.position[5][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e3"
                color="dark"
                piece={props.position[5][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d3"
                color="light"
                piece={props.position[5][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c3"
                color="dark"
                piece={props.position[5][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b3"
                color="light"
                piece={props.position[5][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b3")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a3"
                color="dark"
                piece={props.position[5][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a3")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h4"
                color="dark"
                piece={props.position[4][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g4"
                color="light"
                piece={props.position[4][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f4"
                color="dark"
                piece={props.position[4][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e4"
                color="light"
                piece={props.position[4][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d4"
                color="dark"
                piece={props.position[4][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c4"
                color="light"
                piece={props.position[4][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b4"
                color="dark"
                piece={props.position[4][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b4")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a4"
                color="light"
                piece={props.position[4][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a4")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h5"
                color="light"
                piece={props.position[3][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g5"
                color="dark"
                piece={props.position[3][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f5"
                color="light"
                piece={props.position[3][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e5"
                color="dark"
                piece={props.position[3][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d5"
                color="light"
                piece={props.position[3][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c5"
                color="dark"
                piece={props.position[3][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b5"
                color="light"
                piece={props.position[3][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b5")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a5"
                color="dark"
                piece={props.position[3][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a5")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h6"
                color="dark"
                piece={props.position[2][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g6"
                color="light"
                piece={props.position[2][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f6"
                color="dark"
                piece={props.position[2][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e6"
                color="light"
                piece={props.position[2][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d6"
                color="dark"
                piece={props.position[2][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c6"
                color="light"
                piece={props.position[2][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b6"
                color="dark"
                piece={props.position[2][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b6")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a6"
                color="light"
                piece={props.position[2][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a6")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h7"
                color="light"
                piece={props.position[1][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g7"
                color="dark"
                piece={props.position[1][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f7"
                color="light"
                piece={props.position[1][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e7"
                color="dark"
                piece={props.position[1][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d7"
                color="light"
                piece={props.position[1][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c7"
                color="dark"
                piece={props.position[1][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b7"
                color="light"
                piece={props.position[1][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b7")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a7"
                color="dark"
                piece={props.position[1][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a7")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h8"
                color="dark"
                piece={props.position[0][7]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("h8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="g8"
                color="light"
                piece={props.position[0][6]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("g8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="f8"
                color="dark"
                piece={props.position[0][5]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("f8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="e8"
                color="light"
                piece={props.position[0][4]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("e8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="d8"
                color="dark"
                piece={props.position[0][3]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("d8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="c8"
                color="light"
                piece={props.position[0][2]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("c8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="b8"
                color="dark"
                piece={props.position[0][1]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("b8")}
                onClick={onClickHandler}
              />
            </td>
            <td>
              <Square
                name="a8"
                color="light"
                piece={props.position[0][0]}
                size={props.size}
                hiddenPiece={props.hiddenPiece}
                possibleMove={possibleMoves.includes("a8")}
                onClick={onClickHandler}
              />
            </td>
          </tr>
        </tbody>
      </table>
    );
  }
}

export default ChessBoard;
