import React from "react";
import Square from "./Square";

const ChessBoard = props => {
  if (props.perspective === "white") {
    return (
      <table
        className="center no-padding-no-margin"
        style={{ width: props.size }}
      >
        <tbody>
          <tr>
            <td>
              <Square
                name="a8"
                color="light"
                piece={props.position[0][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b8"
                color="dark"
                piece={props.position[0][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c8"
                color="light"
                piece={props.position[0][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d8"
                color="dark"
                piece={props.position[0][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e8"
                color="light"
                piece={props.position[0][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f8"
                color="dark"
                piece={props.position[0][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g8"
                color="light"
                piece={props.position[0][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h8"
                color="dark"
                piece={props.position[0][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a7"
                color="dark"
                piece={props.position[1][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b7"
                color="light"
                piece={props.position[1][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c7"
                color="dark"
                piece={props.position[1][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d7"
                color="light"
                piece={props.position[1][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e7"
                color="dark"
                piece={props.position[1][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f7"
                color="light"
                piece={props.position[1][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g7"
                color="dark"
                piece={props.position[1][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h7"
                color="light"
                piece={props.position[1][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a6"
                color="light"
                piece={props.position[2][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b6"
                color="dark"
                piece={props.position[2][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c6"
                color="light"
                piece={props.position[2][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d6"
                color="dark"
                piece={props.position[2][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e6"
                color="light"
                piece={props.position[2][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f6"
                color="dark"
                piece={props.position[2][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g6"
                color="light"
                piece={props.position[2][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h6"
                color="dark"
                piece={props.position[2][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a5"
                color="dark"
                piece={props.position[3][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b5"
                color="light"
                piece={props.position[3][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c5"
                color="dark"
                piece={props.position[3][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d5"
                color="light"
                piece={props.position[3][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e5"
                color="dark"
                piece={props.position[3][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f5"
                color="light"
                piece={props.position[3][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g5"
                color="dark"
                piece={props.position[3][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h5"
                color="light"
                piece={props.position[3][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a4"
                color="light"
                piece={props.position[4][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b4"
                color="dark"
                piece={props.position[4][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c4"
                color="light"
                piece={props.position[4][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d4"
                color="dark"
                piece={props.position[4][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e4"
                color="light"
                piece={props.position[4][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f4"
                color="dark"
                piece={props.position[4][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g4"
                color="light"
                piece={props.position[4][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h4"
                color="dark"
                piece={props.position[4][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a3"
                color="dark"
                piece={props.position[5][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b3"
                color="light"
                piece={props.position[5][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c3"
                color="dark"
                piece={props.position[5][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d3"
                color="light"
                piece={props.position[5][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e3"
                color="dark"
                piece={props.position[5][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f3"
                color="light"
                piece={props.position[5][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g3"
                color="dark"
                piece={props.position[5][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h3"
                color="light"
                piece={props.position[5][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a2"
                color="light"
                piece={props.position[6][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b2"
                color="dark"
                piece={props.position[6][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c2"
                color="light"
                piece={props.position[6][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d2"
                color="dark"
                piece={props.position[6][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e2"
                color="light"
                piece={props.position[6][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f2"
                color="dark"
                piece={props.position[6][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g2"
                color="light"
                piece={props.position[6][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h2"
                color="dark"
                piece={props.position[6][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="a1"
                color="dark"
                piece={props.position[7][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b1"
                color="light"
                piece={props.position[7][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c1"
                color="dark"
                piece={props.position[7][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d1"
                color="light"
                piece={props.position[7][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e1"
                color="dark"
                piece={props.position[7][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f1"
                color="light"
                piece={props.position[7][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g1"
                color="dark"
                piece={props.position[7][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="h1"
                color="light"
                piece={props.position[7][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
        </tbody>
      </table>
    );
  } else {
    return (
      <table className="center">
        <tbody>
          <tr>
            <td>
              <Square
                name="h1"
                color="light"
                piece={props.position[7][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g1"
                color="dark"
                piece={props.position[7][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f1"
                color="light"
                piece={props.position[7][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e1"
                color="dark"
                piece={props.position[7][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d1"
                color="light"
                piece={props.position[7][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c1"
                color="dark"
                piece={props.position[7][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b1"
                color="light"
                piece={props.position[7][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a1"
                color="dark"
                piece={props.position[7][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h2"
                color="dark"
                piece={props.position[6][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g2"
                color="light"
                piece={props.position[6][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f2"
                color="dark"
                piece={props.position[6][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e2"
                color="light"
                piece={props.position[6][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d2"
                color="dark"
                piece={props.position[6][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c2"
                color="light"
                piece={props.position[6][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b2"
                color="dark"
                piece={props.position[6][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a2"
                color="light"
                piece={props.position[6][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h3"
                color="light"
                piece={props.position[5][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g3"
                color="dark"
                piece={props.position[5][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f3"
                color="light"
                piece={props.position[5][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e3"
                color="dark"
                piece={props.position[5][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d3"
                color="light"
                piece={props.position[5][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c3"
                color="dark"
                piece={props.position[5][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b3"
                color="light"
                piece={props.position[5][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a3"
                color="dark"
                piece={props.position[5][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h4"
                color="dark"
                piece={props.position[4][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g4"
                color="light"
                piece={props.position[4][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f4"
                color="dark"
                piece={props.position[4][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e4"
                color="light"
                piece={props.position[4][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d4"
                color="dark"
                piece={props.position[4][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c4"
                color="light"
                piece={props.position[4][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b4"
                color="dark"
                piece={props.position[4][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a4"
                color="light"
                piece={props.position[4][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h5"
                color="light"
                piece={props.position[3][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g5"
                color="dark"
                piece={props.position[3][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f5"
                color="light"
                piece={props.position[3][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e5"
                color="dark"
                piece={props.position[3][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d5"
                color="light"
                piece={props.position[3][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c5"
                color="dark"
                piece={props.position[3][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b5"
                color="light"
                piece={props.position[3][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a5"
                color="dark"
                piece={props.position[3][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h6"
                color="dark"
                piece={props.position[2][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g6"
                color="light"
                piece={props.position[2][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f6"
                color="dark"
                piece={props.position[2][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e6"
                color="light"
                piece={props.position[2][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d6"
                color="dark"
                piece={props.position[2][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c6"
                color="light"
                piece={props.position[2][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b6"
                color="dark"
                piece={props.position[2][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a6"
                color="light"
                piece={props.position[2][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h7"
                color="light"
                piece={props.position[1][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g7"
                color="dark"
                piece={props.position[1][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f7"
                color="light"
                piece={props.position[1][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e7"
                color="dark"
                piece={props.position[1][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d7"
                color="light"
                piece={props.position[1][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c7"
                color="dark"
                piece={props.position[1][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b7"
                color="light"
                piece={props.position[1][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a7"
                color="dark"
                piece={props.position[1][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
          <tr>
            <td>
              <Square
                name="h8"
                color="dark"
                piece={props.position[0][7]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="g8"
                color="light"
                piece={props.position[0][6]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="f8"
                color="dark"
                piece={props.position[0][5]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="e8"
                color="light"
                piece={props.position[0][4]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="d8"
                color="dark"
                piece={props.position[0][3]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="c8"
                color="light"
                piece={props.position[0][2]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="b8"
                color="dark"
                piece={props.position[0][1]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
            <td>
              <Square
                name="a8"
                color="light"
                piece={props.position[0][0]}
                lastMove={props.lastMove}
                inCheck={props.inCheck}
                size={props.size}
              />
            </td>
          </tr>
        </tbody>
      </table>
    );
  }
};

export default ChessBoard;
